#!/usr/bin/expect -f
set timeout 30

# Upload the script
spawn scp -P 65002 -o StrictHostKeyChecking=no scratch/update_workflow.cjs u881780269@46.202.158.245:/home/u881780269/domains/whatlify.com/nodejs/update_workflow.cjs
expect {
  "password:" {
    send "qTtSzLzs2Q$\r"
  }
}
expect eof

# Execute the script
spawn ssh -p 65002 -o StrictHostKeyChecking=no u881780269@46.202.158.245
expect {
  "password:" {
    send "qTtSzLzs2Q$\r"
  }
}
expect "$ " {
  send "cd domains/whatlify.com/nodejs && /opt/alt/alt-nodejs22/root/usr/bin/node update_workflow.cjs\r"
}
expect "$ " {
  send "exit\r"
}
expect eof
