#!/usr/bin/expect -f
set timeout 60
spawn ssh -p 65002 -o StrictHostKeyChecking=no u881780269@46.202.158.245
expect {
  "password:" {
    send "qTtSzLzs2Q$\r"
  }
}
expect "$ " {
  send "cd domains/whatlify.com/nodejs && /opt/alt/alt-nodejs20/root/bin/node --import=tsx script/build.ts > build_output.log 2>&1\r"
}
expect "$ " {
  send "cat build_output.log\r"
}
expect "$ " {
  send "exit\r"
}
expect eof
