#!/usr/bin/expect -f
set timeout 90
spawn ssh -p 65002 -o StrictHostKeyChecking=no u881780269@46.202.158.245
expect {
  "password:" {
    send "qTtSzLzs2Q$\r"
  }
}
expect "$ " {
  send "cd domains/whatlify.com/nodejs && git reset --hard && git clean -fd && git pull origin main\r"
}
expect "$ " {
  send "/opt/alt/alt-nodejs20/root/bin/npm run build > build_output.log 2>&1; echo 'Exit status:' $?\r"
}
expect "$ " {
  send "cat build_output.log\r"
}
expect "$ " {
  send "mkdir -p tmp && touch tmp/restart.txt\r"
}
expect "$ " {
  send "exit\r"
}
expect eof
